# Generated by Django 5.2.6 on 2025-09-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_DB',
            fields=[
                ('Cars_Name', models.CharField(max_length=15)),
                ('Carsno', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('model', models.CharField()),
                ('version', models.FloatField()),
            ],
        ),
    ]
